let card = [{
    id:1,
    title:"Дизајн",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"6 лекции",
    lekciite:[{
        id:1,
        date:'21.10.2019',
        subtitle:'Beginning Graphic Design: Fundamentals',
        context:"Learn the fundamentals of graphic design. Eu occaecat esse cillum minim minim anim. In reprehenderit qui incididunt laborum dolore incididunt magna sint. Culpa Lorem cillum elit culpa esse pariatur consectetur ut laboris officia consectetur. Occaecat nulla veniam ea cillum adipisicing. Quis pariatur tempor consectetur amet.",
        link:"https://www.youtube.com/watch?v=YqQx75OPRa0",
    },
    {
        id:2,
        date:'12.02.2019',
        subtitle:'The Worst Mistake In logo Design',
        context:"Learn the biggest logo design mistakes! I also show you how you can combat this mistake and make life a lot easier when figuring out how good your logo truly is. In reprehenderit qui incididunt laborum dolore incididunt magna sint. Culpa Lorem cillum elit culpa esse pariatur consectetur ut laboris officia consectetur. Occaecat nulla veniam ea cillum adipisicing. Quis pariatur tempor consectetur amet.",
        link:"https://www.youtube.com/watch?v=OfIGzbQtFBk",
    },
    {
        id:3,
        date:'05.03.2019',
        subtitle:'Layout & Composition',
        context:"Learn the basics of layout and composition in graphic design. Eu occaecat esse cillum minim minim anim. In reprehenderit qui incididunt laborum dolore incididunt magna sint. Culpa Lorem cillum elit culpa esse pariatur consectetur ut laboris officia consectetur. Occaecat nulla veniam ea cillum adipisicing. Quis pariatur tempor consectetur amet.",
        link:"https://www.youtube.com/watch?v=a5KYlHNKQB8",
    },
    {
        id:4,
        date:'17.04.2019',
        subtitle:'The Logo Design Process | Idea Generation, Sketching, Illustration & finishing.',
        context:"The key segment of this video is the IDEA GENERATION PROCESS. Although I can't teach you creativity. But there are some methods that help you get creative and come up with great logo design concepts. So today I am going to walk you through the process of designing a logo. But I will concentrate the thinking behind the design part.",
        link:"https://www.youtube.com/watch?v=Tbqa-LB5Fx8",
    },
    {
        id:5,
        date:'10.06.2019',
        subtitle:'The Logo Design Process From Start To Finish',
        context:"In this lesson, I will take you through a full logo design project, from start to finish. You will see me sketching, then I will show you how to digitize the sketch and how to make the logo balanced, and you will see much more of my logo design process. Make sure to watch carefully to the end, and then write in the comment section the most valuable information you find it in the tutorial, and I will pick the best three comments and I will mention them in the next tutorial video..",
        link:"https://www.youtube.com/watch?v=J8nabLZKZq0",
    },
    {
        id:6,
        date:'01.09.2019',
        subtitle:'6 Golden Rules Of Layout Design You MUST OBEY',
        context:"Do you know and follow these 6 GOLDEN RULES for layout design? I’m going to demonstrate these rules that every designer should follow, and also show you why they are so crucial within layout and graphic design. Occaecat nulla veniam ea cillum adipisicing. Quis pariatur tempor consectetur amet.",
        link:"https://www.youtube.com/watch?v=EFf9jBs2yfU",
    }]
},

{
    id:2,
    title:"Маркетинг",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"2 лекции",
    lekciite:[{
        id:1,
        date:'04.07.2020',
        subtitle:'2020 Complete Instagram Marketing Masterclass: Become a Pro',
        context:"Learn and master 20 Mega Instagram Marketing Strategies to Grow a Page, Get Real Followers, Sell Online Using Instagram Marketing Sales Funnel. Irure cillum duis nisi laboris et ex sunt adipisicing consectetur labore et incididunt nostrud. Est qui do nulla fugiat labore incididunt ex deserunt commodo veniam anim ea anim officia. In pariatur occaecat est exercitation enim velit excepteur.",
        link:"https://www.udemy.com/course/instagram-marketing-3-tip-get-real-instagram-followers-course-learn/?utm_source=adwords&utm_medium=udemyads&utm_campaign=InstagramMarketing_v.PROF_la.EN_cc.ROW_ti.6252&utm_content=deal4584&utm_term=_._ag_85479008874_._ad_437497336485_._kw__._de_c_._dm__._pl__._ti_dsa-774930039049_._li_1007850_._pd__._&matchtype=b&gclid=EAIaIQobChMIoYTF3IL66wIVh8_tCh2NGwYDEAAYASAAEgK3wPD_BwE",
        },
        {   
        id:2,
        date:'21.08.2020',
        subtitle:'Copywriting Headline Masterclass',
        context:"Do you want to learn the psychology behind some of the most successful headlines in the entire history of marketing? Do you want to learn how to write quickly and easily extremely powerful headlines for your blog posts, social media posts, email subject line, eBook, squeeze and sales pages? Well, if your answer is “yes” to even one of these questions then this course will transform you into the best headline writer you could possibly be! Read on…",
        link:"https://www.udemy.com/course/copywriting-how-to-write-copywriting-headlines/",
}]
},

{
    id:3,
    title:"UX/UI",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"3 лекции",
    lekciite:[{
        id:1,
        date:'14.03.2019',
        subtitle:'User Experience Design Essentials - Adobe XD UI UX Design',
        context:"Hi there! My name is Dan & I’m an Adobe Certified Instructor. I’m here to help you learn Adobe XD efficiently and comprehensively. XD is a fantastic design tool used by industry professionals to product high quality & functional mockups. By the end of this course, you will be able to produce practical and effective User Experience (UX) and User Interface (UI) designs.",
        link:"https://www.udemy.com/course/ui-ux-web-design-using-adobe-xd/",
    },
    {
        id:2,
        date:'21.10.2019',
        subtitle:'The Complete App Design Course - UX, UI and Design Thinking',
        context:"The App Design Course is great for people with absolutely no design experience or experienced designers who want to get up to speed quickly with mobile app design. We'll introduce you to the art of making beautiful apps. We'll explore key UI and UX concepts that are essential to building good looking and easy to use apps that are loved by users.",
        link:"https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/",
    },
    {
        id:3,
        date:'01.11.2019',
        subtitle:'Master Digital Product Design: UX Research & UI Design',
        context:"Digital products are more abstract and complex than any product we've designed before. People are using their digital devices faster, with less conscious thought and more distracted than ever in history. These issues present new challenges that require a new kind of design team to address. These design teams need to understand a complex range of behavioral psychology, perception, creativity, business. They need to understand what has come before, the history of design didn't start with the iPhone. The history of product design started with the history of products!",
        link:"https://www.udemy.com/course/master-digital-product-design-ux-research-ui-design/",
    },
    ]
},
{
    id:4,
    title:"Data Science",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"5 лекции",
    lekciite:[{
        id:1,
        date:'01.03.2020',
        subtitle:'The Data Science Course 2020: Complete Data Science Bootcamp',
        context:"The course provides the entire toolbox you need to become a data scientist. Impress interviewers by showing an understanding of the data science field. Understand the mathematics behind Machine Learning (an absolute must which other courses don’t teach!)",
        link:"https://www.udemy.com/course/the-data-science-course-complete-data-science-bootcamp/",
    },
    {
        id:2,
        date:'15.07.2020',
        subtitle:'Data Science A-Z™: Real-Life Data Science Exercises Included',
        context:"What you'll learn: Successfully perform all steps in a complex Data Science project, Perform Data Mining in Tableau, Apply Ordinary Least Squares method to Create Linear Regressions, Assess the Adjusted R-Squared for all types of models and more...",
        link:"https://www.udemy.com/course/datascience/",
    },
    {
        id:3,
        date:'07.08.2020',
        subtitle:'Unsupervised Deep Learning in Python',
        context:"This course is the next logical step in my deep learning, data science, and machine learning series. I’ve done a lot of courses about deep learning, and I just released a course about unsupervised learning, where I talked about clustering and density estimation. So what do you get when you put these 2 together? Unsupervised deep learning!",
        link:"https://www.udemy.com/course/unsupervised-deep-learning-in-python/",
    },
    {
        id:4,
        date:'01.09.2020',
        subtitle:'Deep Learning Prerequisites: Logistic Regression in Python',
        context:"This course is a lead-in to deep learning and neural networks - it covers a popular and fundamental technique used in machine learning, data science and statistics: logistic regression. We cover the theory from the ground up: derivation of the solution, and applications to real-world problems. We show you how one might code their own logistic regression module in Python.",
        link:"https://www.udemy.com/course/data-science-logistic-regression-in-python/",
    },
    {
        id:5,
        date:'12.09.2020',
        subtitle:'R Programming A-Z™: R For Data Science With Real Exercises!',
        context:"Learn R Programming by doing! There are lots of R courses and lectures out there. However, R has a very steep learning curve and students often get overwhelmed. This course is different! This course is truly step-by-step. In every new tutorial we build on what had already learned and move one extra step forward. After every video you learn a new valuable concept that you can apply right away. And the best part is that you learn through live examples.",
        link:"https://www.udemy.com/course/r-programming/",
    }]
},
{
    id:5,
    title:"Бизнис",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"4 лекции",
    lekciite:[{
        id:1,
        date:'21.02.2020',
        subtitle:'The Product Management for AI & Data Science Course 2020',
        context:"This course gives you a fairly unique opportunity. You will have the chance to learn from somebody who has been in the industry and who has actually seen AI & data science implemented at the highest level. Your instructor, Danielle Thé, is a Senior Product Manager for Machine Learning with a Master’s in Science of Management, and years of experience as a Product Manager, and Product Marketing Manager in the tech industry for companies like Google and Deloitte Digital.",
        link:"https://www.udemy.com/course/the-product-management-for-data-science-ai-course/",
    },
{
    id:2,
    date:'01.03.2020',
    subtitle:'Introduction to Business Analytics 2020',
    context:"This course is an invaluable journey, in which we will layout the foundations of your superior business analytics skills. You will start developing abilities that are highly necessary in any type of business environment, but particularly so when working for a large blue-chip corporation -running a complex business.",
    link:"https://www.udemy.com/course/introduction-to-business-analytics/",
},
{
    id:3,
    date:'11.05.2020',
    subtitle:'Learn Business Data Analysis with SQL and Tableau',
    context:"As most of the business data stored in relational databases, learning SQL is essential for anyone wants to be a data analyst or scientist. SQL is the main tool used to manipulate data in relational databases, so mastering SQL is necessary to perform deep data analyses.",
    link:"https://www.udemy.com/course/learn-business-data-analysis-with-sql-and-tableau/",
},
{
    id:4,
    date:'21.07.2020',
    subtitle:'Tableau for Business Analytics and Marketing',
    context:"Visualizing marketing data through Tableau can be a game changer. It can be the skill to take your career to the next level. We cover the theory from the ground up: derivation of the solution, and applications to real-world problems. We show you how one might code their own logistic regression module in Python.",
    link:"https://www.udemy.com/course/tableau-for-marketing/",
},
]
},

{
    id:6,
    title:"Програмирање",
    text:"Студии на случај: ќе научиш како да се справуваш со маркетинг предизвиците во дигиталниот свет и ќе ги стекнеш најбараните вештини во моментот.",
    lekcii:"6 лекции",
    lekciite:[{
        id:1,
        date:'21.02.2020',
        subtitle:'Java Programming Masterclass for Software Developers',
        context:"You’ve just stumbled upon the most complete, in-depth Java programming course online. With over 480,000 students enrolled and tens of thousands of 5-star reviews to date, these comprehensive java tutorials cover everything you’ll ever need.",
        link:"https://www.udemy.com/course/java-the-complete-java-developer-course/",
    },
    {
        id:2,
        date:'15.02.2020',
        subtitle:'Learn Ethical Hacking From Scratch',
        context:"VThis course is highly practical but it won't neglect the theory; we'll start with ethical hacking basics, breakdown the different penetration testing fields and install the needed software (on Windows, Linux and Mac OS X), then we'll dive and start hacking straight away. From here onwards you'll learn everything by example, by analysing and exploiting different systems such as networks, servers, clients, websites .....etc, so we'll never have any boring dry theoretical lectures.",
        link:"https://www.udemy.com/course/learn-ethical-hacking-from-scratch/",
    },
    {
        id:3,
        date:'17.05.2020',
        subtitle:'The Complete Cyber Security Course',
        context:"This course covers the fundamental building blocks of your required skill set - You will understand the threat and vulnerability landscape through threat modeling and risk assessments. We cover the theory from the ground up: derivation of the solution, and applications to real-world problems. We show you how one might code their own logistic regression module in Python.",
        link:"https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/",
    },
    {
        id:4,
        date:'03.07.2020',
        subtitle:'Learn Python Programming Masterclass',
        context:"VThis course is aimed at complete beginners who have never programmed before, as well as existing programmers who want to increase their career options by learning Python. The fact is, Python is one of the most popular programming languages in the world – Huge companies like Google use it in mission critical applications like Google Search.",
        link:"https://www.udemy.com/course/python-the-complete-python-developer-course/",
    },
    {
        id:5,
        date:'21.07.2020',
        subtitle:'The Python Mega Course: Build 10 Real World Applications',
        context:"The Python Mega Course is the most practical course you will find on the web today. This is the course where you will learn to build actual desktop programs, web applications, and even mobile apps entirely in Python 3. Here are the 10 apps you are going to build...",
        link:"https://www.udemy.com/course/the-python-mega-course/",
    },
    {
        id:6,
        date:'06.09.2020',
        subtitle:'REST APIs with Flask and Python',
        context:"Welcome to one of the best resources online on creating REST APIs. I'm Jose, and I'm a software engineer; here to help you truly understand and develop your skills in web and REST API development with Python, using Flask...",
        link:"https://www.udemy.com/course/rest-api-flask-and-python/",
    }]
}];

export default card;